name: 'setup'
description: Setup project environment

inputs:
  gradle-cache-disabled:
    description: "When 'true', all Gradle caching is disabled."
    default: 'false'
  gradle-cache-encryption-key:
    description: 'A base64 encoded AES key used to encrypt the Gradle configuration-cache data.'

runs:
  using: 'composite'

  steps:
    - name: 'Set up JDK'
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 21

    - name: 'Redirect caches to fast D: drive on Windows'
      if: runner.os == 'Windows'
      shell: cmd
      # region WORKAROUND https://youtrack.jetbrains.com/issue/KT-79144
      #
      # When a fix is available, remove the following line and uncomment those below.
      run: echo KONAN_DATA_DIR=C:\Users\runneradmin\.konan>>%GITHUB_ENV%
      # run: |
      #   mkdir D:\.gradle
      #   mklink /D C:\Users\runneradmin\.gradle D:\.gradle
      #
      #   mkdir D:\.konan
      #   mklink /D C:\Users\runneradmin\.konan D:\.konan
      #   echo KONAN_DATA_DIR=D:\.konan>>%GITHUB_ENV%
      #
      # endregion

    - name: 'Setup Kotlin/Native cache directory on Unix-like systems'
      if: runner.os != 'Windows'
      shell: bash
      run: |
        echo "KONAN_DATA_DIR=${HOME}/.konan" >> $GITHUB_ENV

    # Enable configuration-cache reuse with included builds – https://github.com/gradle/actions/issues/21
    - name: 'Cache build-settings/build'
      uses: actions/cache@v4
      with:
        path: build-settings/build
        key: build-settings-${{ hashFiles('build-settings/src/**', 'build-settings/*.kts') }}

    - name: 'Cache build-logic/build'
      uses: actions/cache@v4
      with:
        path: build-logic/build
        key: build-logic-${{ hashFiles('build-logic/src/**', 'build-logic/*.kts') }}

    - name: 'Set up Gradle'
      uses: gradle/actions/setup-gradle@v4
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
        build-scan-terms-of-use-agree: 'yes'
        cache-disabled: ${{ inputs.gradle-cache-disabled }}
        cache-encryption-key: ${{ inputs.gradle-cache-encryption-key }}
        # Enable cache writes for branches other than 'main'.
        cache-read-only: ${{ !(github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/releases/') || startsWith(github.ref, 'refs/heads/ci-experiments/')) }}

    - name: 'Cache Kotlin/Native'
      uses: actions/cache@v4
      with:
        path: ${{ env.KONAN_DATA_DIR }}
        key: konan-${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts', 'gradle/*.versions.toml', 'gradle.properties') }}
        restore-keys: |
          konan-${{ runner.os }}-gradle-
