== TestBalloon Examples

=== Using the Core Library

The link:../examples/framework-core[examples/framework-core] directory is intended to provide source code samples for all TestBalloon features in link:../examples/framework-core/src/commonTest[commonTest].

To run them all:

* `gradlew --quiet :examples:core:cleanAllTests :examples:core:allTests`

As usual, you can run examples for a single target:

* `gradlew --quiet :examples:framework-core:cleanAllTests :examples:framework-core:jvmTest`
* `gradlew --quiet :examples:framework-core:cleanAllTests :examples:framework-core:jsNodeTest`
* `gradlew --quiet :examples:framework-core:cleanAllTests :examples:framework-core:jsBrowserTest`
* `gradlew --quiet :examples:framework-core:cleanAllTests :examples:framework-core:wasmJsNodeTest`
* `gradlew --quiet :examples:framework-core:cleanAllTests :examples:framework-core:wasmJsBrowserTest`
* `gradlew --quiet :examples:framework-core:cleanAllTests :examples:framework-core:wasmWasiNodeTest`
* `gradlew --quiet :examples:framework-core:cleanAllTests :examples:framework-core:linuxX64Test`


=== Using Integrations

==== Kotest Assertions

Some features of the Kotest Assertions library require extra setup, e.g. soft assertions. The link:../testBalloon-integration-kotest-assertions[testBalloon-integration-kotest-assertions] directory demonstrates how to use those with TestBalloon.
