== IDE and Build Tool Interoperability

=== JUnit Platform

==== General

https://junit.org/junit5/docs/current/user-guide/#test-engines[Test
Engines] must

* discover tests from an
https://junit.org/junit5/docs/current/api/org.junit.platform.engine/org/junit/platform/engine/EngineDiscoveryRequest.html[`EngineDiscoveryRequest`],
yielding a hierarchy of test descriptors, and
* execute tests according to an
https://junit.org/junit5/docs/current/api/org.junit.platform.engine/org/junit/platform/engine/ExecutionRequest.html[`ExecutionRequest`],
starting at the root test descriptor and observing tests events via a
listener (which also observes the discovery of new tests, if these are
dynamically registered during execution).

A
https://junit.org/junit5/docs/current/api/org.junit.platform.engine/org/junit/platform/engine/TestDescriptor.html[test
descriptor] describes a node in the test hierarchy (a suite or a test). Each
node has a
https://junit.org/junit5/docs/current/api/org.junit.platform.engine/org/junit/platform/engine/UniqueId.html[unique
identifier], comprised of a list of type/value segments. Segment type
and value are non-empty strings. Typical segment types are ``test``,
``class``, ``engine``, but there appears to be no defined scheme and
``engine`` https://github.com/junit-team/junit5/discussions/3551[seems
to be the only stable name].

==== Test Discovery

An
https://junit.org/junit5/docs/current/api/org.junit.platform.engine/org/junit/platform/engine/EngineDiscoveryRequest.html[`EngineDiscoveryRequest`]

* selects test nodes via
** `ClassSelector`: named class,
** `MethodSelector`: named method (plus optional signature),
** `UniqueIdSelector`: unique identifier,
** https://junit.org/junit5/docs/current/api/org.junit.platform.engine/org/junit/platform/engine/DiscoverySelector.html[others,
e.g.]: classpath, directory, file, module, package, URI, and
* filters test nodes via
** `ClassNameFilter`: list of class name RE patterns to include and/or
exclude,
** `PackageNameFilter`: list of package name RE patterns to include
and/or exclude.

The https://docs.gradle.org/current/userguide/java_testing.html[Gradle
test task] uses

* the selectors
** `ClassSelector` (Gradle passes a selector for every class it finds,
not knowing which ones are test classes),
** `UniqueIdSelector` (Gradle Enterprise: distribute tests across
processes), and
* the filter
** `ClassNameFilter` (if
https://docs.gradle.org/current/userguide/java_testing.html#test_filtering[test
filtering] is used).

Kotest supports

* the selectors
** `PackageSelector`,
** `ClassSelector`,
** `UniqueIdSelector` (added by a Gradle member to support distributing
tests across processes in Gradle Enterprise), and
* the filters
** `ClassNameFilter`,
** `PackageNameFilter`.

==== Source Code Test Discovery (IDE Support)

https://junit.org/junit5/docs/current/api/org.junit.platform.commons/org/junit/platform/commons/annotation/Testable.html[The
Testable annotation] exists to make IDEs aware of elements which can be
executed as a test or test container. It is intended for use cases where
full discovery via compiled code is unavailable. (IntelliJ IDEA
https://github.com/JetBrains/intellij-community/blob/65cf881f35eea8a594b9375651a7a03823f09723/java/execution/impl/src/com/intellij/execution/junit/JUnitUtil.java#L42[contains
some support] for it. Is this is actually used for Kotlin?)

=== IntelliJ IDEA

The IDE runs tests via regular Gradle invocations.

When selecting a single test in the run window, the IDE runs it via a
`--tests` filter, e.g. `--tests "com.example.TestSuite2"`, if

* the test ran via JUnit Platform, or
* the IntelliJ XML log contains a `descriptor` tag with a `classname`
attribute supplying a fully qualified class name _and_ the test run
respects the `--tests` filter.

The IDE
https://github.com/JetBrains/intellij-community/blob/8032aef848d1edf5771e442cb749e047b885876c/plugins/gradle/java/src/action/GradleRerunFailedTestsAction.kt[re-runs
failed tests] by analyzing the test files’ source code and
https://github.com/JetBrains/intellij-community/blob/8032aef848d1edf5771e442cb749e047b885876c/plugins/gradle/java/src/execution/test/runner/TestGradleConfigurationProducerUtil.kt#L15[creating
a Gradle invocation with filters].
