plugins {
    id("buildLogic.multiplatform-all")
    id("buildLogic.publishing-multiplatform")
}

description = "Core library for the TestBalloon framework"

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                api(projects.testBalloonFrameworkAbstractions)
                // kotlin-test provides the startUnitTests() function required by Kotlin/Wasm. This could also
                // be generated by the compiler plugin, but doing so would prevent library consumers from using
                // kotlin-test for assertions due to a then-redefined symbol for startUnitTests().
                implementation(kotlin("test"))
                api(libs.org.jetbrains.kotlinx.coroutines.core)
                api(libs.org.jetbrains.kotlinx.coroutines.test)
                implementation(libs.org.jetbrains.kotlinx.datetime)
                implementation(libs.org.jetbrains.kotlinx.atomicfu)
            }
        }

        jvmMain {
            dependencies {
                implementation(libs.org.junit.platform.engine)
            }
        }

        jvmTest {
            dependencies {
                implementation(libs.org.jetbrains.kotlinx.coroutines.swing)
            }
        }
    }
}

tasks.withType<Test>().configureEach {
    // https://docs.gradle.org/current/userguide/java_testing.html
    useJUnitPlatform {
        excludeEngines("de.infix.testBalloon")
    }
}
