name: 'CI: Publish a release'

on:
  release:
    types: [ released, prereleased ]

jobs:
  publish:
    if: github.repository == 'infix-de/testBalloon'
    runs-on: macOS-latest

    steps:
      - name: 'Check out the project'
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          gradle-cache-disabled: true

      - name: 'Publish to MavenCentral'
        run: ./gradlew publishToMavenCentral --no-configuration-cache -Pversion=${{ github.event.release.tag_name }}
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
