name: 'CI: Push on main or release branch'

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
      - 'ci-experiments/**'
    paths-ignore:
      - '*.adoc'
      - '*.md'
      - '*.txt'
      - '.editorconfig'
      - '.gitignore'
      - 'comparisons/**'
      - 'documentation/**'
      - 'examples/**'
      - 'experiments/**'

jobs:
  validate:
    name: 'Validate the build'
    uses: ./.github/workflows/validate.yml
    secrets: inherit
