name: "Validate the build"

on:
  workflow_call

jobs:
  validate-primary:
    name: "Validate on primary runner"
    runs-on: ubuntu-latest

    steps:
      - name: "Check out the project"
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Validate
        run: ./gradlew prePublishingTestsAllTests

  validate-secondary:
    name: "Validate on secondary runners"
    needs: [ validate-primary ]
    runs-on: macos-latest

    steps:
      - name: "Check out the project"
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Validate
        run: ./gradlew prePublishingTestsAllTests
